In [2]:
import pandas as pd
import numpy as np
import sklearn.preprocessing 
import sklearn.ensemble
from sklearn.preprocessing import OneHotEncoder


In [3]:
rawdata=pd.read_csv('CrowdstormingDataJuly1st.csv')
utaka=rawdata[[name=="john-utaka" for name in rawdata.playerShort]]
utaka.shape

(150, 28)

In [4]:
rawdata = rawdata.ix[~(rawdata.photoID.isnull())]

In [5]:
rawdata=rawdata.ix[~(rawdata.meanIAT.isnull())]


In [111]:
rawdata[rawdata['skinColor']==0.625]

playerShort                  player                 club  \
51          alexandre-alphonse      Alexandre Alphonse          Stade Brest   
218             yacine-brahimi          Yacine Brahimi           Granada CF   
222           youssef-el-arabi        Youssef El-Arabi           Granada CF   
444                junior-diaz             Júnior Díaz      1. FSV Mainz 05   
451                junior-diaz             Júnior Díaz      1. FSV Mainz 05   
459                ammar-jemal             Ammar Jemal           AC Ajaccio   
465            florent-malouda         Florent Malouda           Chelsea FC   
527             julio-baptista          Júlio Baptista            Málaga CF   
533         alexandre-alphonse      Alexandre Alphonse          Stade Brest   
536                ammar-jemal             Ammar Jemal           AC Ajaccio   
651         alexandre-alphonse      Alexandre Alphonse          Stade Brest   
743                junior-diaz             Júnior Díaz      1. FSV Mainz 05   
761         alexandre-alphonse      Alexandre Alphonse          Stade Brest   
893            florent-malouda         Florent Malouda           Chelsea FC   
897               franck-beria            Franck Béria            Lille OSC   
915               glen-johnson            Glen Johnson         Liverpool FC   
967               jimmy-briand            Jimmy Briand       Olympique Lyon   
984             julio-baptista          Júlio Baptista            Málaga CF   
1012                 loic-remy               Loïc Rémy  Olympique Marseille   
1059             michel-bastos           Michel Bastos       Olympique Lyon   
1070                   naldo_2                   Naldo        VfL Wolfsburg   
1288           florent-malouda         Florent Malouda           Chelsea FC   
1302              glen-johnson            Glen Johnson         Liverpool FC   
1335              jimmy-briand            Jimmy Briand       Olympique Lyon   
1562              glen-johnson            Glen Johnson         Liverpool FC   
1598        alexandre-alphonse      Alexandre Alphonse          Stade Brest   
1689           florent-malouda         Florent Malouda           Chelsea FC   
1729                joel-matip              Joel Matip        FC Schalke 04   
1753                 loic-remy               Loïc Rémy  Olympique Marseille   
1817                 ramalho_4                 Ramalho      Athletic Bilbao   
...                        ...                     ...                  ...   
144616            glen-johnson            Glen Johnson         Liverpool FC   
144706            jimmy-briand            Jimmy Briand       Olympique Lyon   
144712              joel-matip              Joel Matip        FC Schalke 04   
144741             junior-diaz             Júnior Díaz      1. FSV Mainz 05   
144759       kieran-richardson       Kieran Richardson            Fulham FC   
144784               loic-remy               Loïc Rémy  Olympique Marseille   
144857     maxim-choupo-moting     Maxim Choupo-Moting      1. FSV Mainz 05   
144870       michael-mancienne       Michael Mancienne         Hamburger SV   
144875           michel-bastos           Michel Bastos       Olympique Lyon   
144895                 naldo_2                   Naldo        VfL Wolfsburg   
145085  theodor-gebre-selassie  Theodor Gebre Selassie        Werder Bremen   
145257             ammar-jemal             Ammar Jemal           AC Ajaccio   
145276          yacine-brahimi          Yacine Brahimi           Granada CF   
145294             ammar-jemal             Ammar Jemal           AC Ajaccio   
145470          yacine-brahimi          Yacine Brahimi           Granada CF   
145476        youssef-el-arabi        Youssef El-Arabi           Granada CF   
145495     maxim-choupo-moting     Maxim Choupo-Moting      1. FSV Mainz 05   
145499             ammar-jemal             Ammar Jemal           AC Ajaccio   
145554         florent-malouda         Florent Malouda           Chel

In [411]:
rawdata.isnull().sum()


playerShort         0
player              0
club                0
leagueCountry       0
birthday            0
height             46
weight            753
position         8454
games               0
victories           0
ties                0
defeats             0
goals               0
yellowCards         0
yellowReds          0
redCards            0
photoID             0
rater1              0
rater2              0
refNum              0
refCountry          0
Alpha_3             0
meanIAT             0
nIAT                0
seIAT               0
meanExp             0
nExp                0
seExp               0
dtype: int64

In [6]:
rawdata['skinColor']=(rawdata['rater1']+rawdata['rater2'])/2
rawdata.shape

(124468, 29)

In [413]:
rawdata['games']


0         1
1         1
5         1
6         1
7         1
8         1
9         1
10        2
11        1
12        1
13        1
14        1
15        1
16        1
17        1
18        1
19        1
20        1
21        1
22        1
23        1
24        1
25        1
26        1
27        1
28        2
29        2
30        1
31        1
32        1
         ..
145998    1
145999    1
146000    1
146001    1
146002    1
146003    1
146004    1
146005    1
146006    1
146007    1
146008    1
146009    3
146010    1
146011    1
146012    1
146013    1
146014    2
146015    1
146016    3
146017    1
146018    1
146019    1
146020    1
146021    1
146022    1
146023    1
146024    1
146025    1
146026    1
146027    1
Name: games, dtype: int64

In [73]:
csfier = sklearn.ensemble.RandomForestClassifier(n_estimators=50,criterion='entropy',max_depth=4,min_samples_leaf=100)


In [53]:

rawdata = rawdata.ix[~(rawdata.height.isnull())]
rawdata = rawdata.ix[~(rawdata.weight.isnull())]
rawdata = rawdata.ix[~(rawdata.position.isnull())]

treatedData=rawdata.drop(['rater1','rater2'],axis=1)
treatedData.isnull().sum()
treatedData=treatedData.drop(['playerShort','club','birthday','photoID'],axis=1)


In [54]:
le = sklearn.preprocessing.LabelEncoder()
le.fit(treatedData['Alpha_3'])
ab=le.transform(treatedData['Alpha_3'])
treatedData['Alpha_3']=ab
le.fit(treatedData['leagueCountry'])
bc=le.transform(treatedData['leagueCountry'])
treatedData['leagueCountry']=bc
le.fit(treatedData['position'])
cde=le.transform(treatedData['position'])
treatedData['position']=cde

In [417]:
sortedcolors=colorseries.sort_values()
sortedcolors

AttributeError: 'numpy.ndarray' object has no attribute 'sort_values'

In [55]:
treatedData=treatedData.sort(columns='player', axis=0)
colorseries=treatedData['skinColor']
players=pd.unique(treatedData['player'])
newData=pd.DataFrame()
frames=[]
for p in players:
    playerFrame=treatedData[treatedData['player']==p]
    playerFrame['yellowCount']=playerFrame['yellowCards'].sum()
    playerFrame['goalCount']=playerFrame['goals'].sum()
    playerSerie=playerFrame.head(1)
    frames.append(playerSerie)
newData=pd.concat(frames)
colorSeries=newData['skinColor']
treatedData=treatedData.drop(['player','skinColor'],axis=1)
newData=newData.drop(['player','skinColor'],axis=1)
newData

/Applications/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':
/Applications/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Applications/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


leagueCountry  height  weight  position  games  victories  ties  \
71772               3   172.0    67.0         7      3          2     0   
62717               3   188.0    82.0         5      1          1     0   
7485                3   171.0    69.0         2      1          0     0   
116099              3   182.0    78.0         2      1          0     0   
24124               3   190.0    88.0         5      1          0     0   
12941               3   187.0    77.0         2      3          2     1   
144357              3   181.0    77.0         4      2          1     1   
35976               3   186.0    82.0         1      9          0     4   
90497               1   188.0    92.0         1      1          1     0   
141466              3   183.0    80.0         1      1          1     0   
21669               3   175.0    73.0         0      1          1     0   
96117               3   192.0    86.0         1      4          1     2   
24151               3   192.0    85.0         1     12          4     3   
22870               3   182.0    73.0         0      8          5     3   
66883               0   176.0    69.0         3      1          1     0   
44539               3   188.0    81.0         1      1          0     0   
29473               1   184.0    76.0         1      7          2     4   
127135              0   180.0    74.0         6      1          1     0   
60803               3   192.0    84.0         1      5          2     1   
18001               1   184.0    81.0         5      2          1     1   
111223              3   176.0    74.0         6      1          0     0   
5458                3   173.0    72.0         4      6          3     2   
46947               3   184.0    82.0         2      2          1     0   
81433               3   184.0    80.0         5     10          3     4   
71792               3   184.0    79.0         9      1          1     0   
32344               3   189.0    76.0         2      1          1     0   
71794               3   185.0    77.0         1      5          1     3   
6962                3   186.0    81.0         5      1          0     0   
141198              3   189.0    85.0         5      1          1     0   
89696               3   182.0    82.0         1      1          1     0   
...               ...     ...     ...       ...    ...        ...   ...   
20846               1   181.0    70.0         6      1          0     0   
73756               0   191.0    90.0         4      2          2     0   
41133               1   175.0    70.0        11      1          0     0   
60118               1   185.0    79.0         0      4          4     0   
125871              0   175.0    69.0         4      4          1     2   
117137              2   164.0    55.0         0      1          0     1   
67673               0   178.0    70.0         0      1          0     1   
59016               0   190.0    87.0         1      1          0     0   
65369               1   174.0    75.0         0      1          1     0   
222                 3   180.0    75.0         2      1          0     1   
27255               2   179.0    70.0         0      1          0     1   
35136               2   174.0    72.0         9      2          2     0   
53764               2   186.0    71.0         4      2          0     1   
88984               2   175.0    67.0         9      1          0     1   
118586              2   187.0    88.0         5      2          1     0   
3114                1   192.0    84.0         2      5          2     3   
75928               2   172.0    69.0         0      4          1     0   
140406              0   181.0    76.0         8      3          0     1   
85411               2   175.0    67.0         7      5          1     1   
80221               1   182.0    76.0         1      1          0     0   
67772               3   190.0    76.0         1      1          0     1   
15066               2   193.0    

In [56]:
newData=newData.drop(['yellowReds','redCards','nIAT','seIAT','nExp','seExp','games','victories','ties','defeats'],axis=1)

In [59]:
newData=newData.drop(['refNum','refCountry','meanIAT','meanExp','yellowCards','Alpha_3','goals'],axis=1)


ValueError: labels ['refNum' 'refCountry' 'meanIAT' 'meanExp' 'yellowCards' 'Alpha_3'] not contained in axis

In [60]:
newData=newData.drop(['goals'],axis=1)

In [108]:
newData[]

array([3, 1, 0, 2])

In [62]:
le.fit(colorSeries)
cd=le.transform(colorSeries)
colorSeries=cd


In [39]:
treatedData.loc[19]

player           Ivan Obradović
leagueCountry                 3
height                      181
weight                       74
position                      6
games                         1
victories                     1
ties                          0
defeats                       0
goals                         0
yellowCards                   1
yellowReds                    0
redCards                      0
refNum                        4
refCountry                    4
Alpha_3                      85
meanIAT                0.325185
nIAT                        127
seIAT                0.00329681
meanExp                0.538462
nExp                        130
seExp                 0.0137522
skinColor                 0.125
Name: 19, dtype: object

In [64]:
import math
def split(trainratio,data):
    trainSetSize=math.ceil((data.shape[0])*trainratio)
    testSetSize=data.shape[0]-trainSetSize
    trainSet=data.loc[range(trainSetSize)]
    testSet=data.loc[range(trainSetSize,data.shape[0])]
    return trainSet,testSet

newData.index=range(newData.shape[0])    
sss=split(0.7,newData)
sss[0].shape

(985, 6)

In [423]:
colorseries[range(7)]

array([2, 2, 2, 2, 2, 2, 2])

In [93]:
newData[index]

NameError: name 'index' is not defined

In [113]:
colorSeries

array([2, 2, 2, ..., 2, 0, 0])

In [103]:
csfier.fit(sss[0],colorSeries[range(sss[0].shape[0])])
csfier.score(sss[1],colorSeries[range(sss[0].shape[0],newData.shape[0])])

0.31116389548693585

In [96]:
newData.columns

Index(['leagueCountry', 'height', 'weight', 'position', 'yellowCount',
       'goalCount'],
      dtype='object')

In [104]:
csfier.feature_importances_


array([ 0.42799014,  0.16814926,  0.11216431,  0.08349424,  0.11294898,
        0.09525307])